tasks:
  build:
    steps:
    - checkout
    # commands to build Beauty & Spa website
    - commands:
      - gem install bundler
      - rm Gemfile.lock
      - bundle install
      - JEKYLL_ENV=production bundle exec jekyll build

    # commands to upload static pages folder to AWS S3
    - commands:
      - aws s3 rm s3://$project-0001--recursive
      - aws s3 cp _site s3://$http://project-0001.s3-website-us-east-1.amazonaws.com --recursive
      if: branch == 'main'
