tasks:
    build-and-deploy:
      steps:
      - checkout
      # commands to build jekyll website
      - commands:
        - bundle install
        - JEKYLL_ENV=production bundle exec jekyll build
      # Commands to upload static pages folder to AWS S3 or ftp
      # Set AWS access key & secrets environment variables under 
      # Razorops dashboard project pipelines 
      - commands:
        - aws s3 rm s3://$project-0001--recursive
        - aws s3 cp _site s3://$http://project-0001.s3-website-us-east-1.amazonaws.com --recursive
        if: branch == 'master'
