tasks:
  build:
    steps:
      - checkout
        commands:
          # Install necessary tools (assuming they are not already installed)
          - sudo apt-get update
          - sudo apt-get install -y awscli git

          # Clone the GitHub repository
          - git clone https://gh repo clone Ismailk03/project
          # Set AWS credentials
          - aws configure set aws_access_key_id $AKIAUEEQUF2IJSDZM6XP
          - aws configure set aws_secret_access_key $DYUSzIoyVBTYU57ePCQGjSjUI6icoltT0rsujTQR
          
          # Deploy to S3 bucket
          - aws s3 sync your-html-repo/ s3://project-0001 
      if: branch == 'master'  # Adjust the branch name as needed
