tasks:
  build:
    steps:
      - checkout

      # Install dependencies and build Jekyll site
      - commands:
          - gem install bundler
          - bundle install
          - bundle exec jekyll build
  deploy:
    steps:
      - commands:
          # Set AWS credentials from Razorops secrets
          - aws configure set aws_access_key_id $AKIAUEEQUF2INUWXSMFS
          - aws configure set aws_secret_access_key $gglFtc0Aq7XdMWNDaPHLhVOka4QWXkRrAvZmi8XZ
          
          # Sync _site directory to S3 bucket
          - aws s3 sync _site/ s3://project-0001 --delete
      if: branch == 'master'
